### ISSUE TITLE
Running with Poetry

### ISSUE THREAD

**Issue by Spectre5** [chriskiehl/Gooey#670]
# Environment
 - OS: Ubuntu 20.04 (also tried Windows 10)
 - Python Version: 3.7 and 3.8
 - Gooey Version: 1.0.8
- Assuming poetry (^1.1.0) is installed and there is a directory structure like this:
![Directory](https://user-images.githubusercontent.com/31610422/106708453-c0970a80-65a7-11eb-8332-dec88fdf973a.png)
- The `__init__.py` file is empty, the `simple_demo.py` is straight from the gooey examples repository, and the `pyproject.toml` file is:
  ```toml
  [tool.poetry]
  name = "gooey_test"
  version = "0.0.1"
  description = "test"
  authors = [""]
  
  [tool.poetry.dependencies]
  python = "^3.7"
  Gooey = "^1.0.8"
  
  [tool.poetry.scripts]
  gooey_test = 'gooey_test.simple_demo:main'
  ```
- Then execute these lines to get the screen shots shown below.
  ```bash
  poetry install
  poetry run gooey_test
  ```

# Issue 1 (Linux only, low priority)
The cancel button is the wrong size and the text in all buttons is not centered, but shifted a little bit to the left and up.
![StartScreen](https://user-images.githubusercontent.com/31610422/106707624-60ec2f80-65a6-11eb-9e66-10aacbbffb28.png)

# Issue 2 (Linux and Windows, high priority)
See the image --- the command doesn't run, regardless of any inputs on the first screen.  I've dumped the config file (`@Gooey(dump_build_config=True)`) and I see the line below for the target.  Due to how Poetry run the files, this doesn't exist.  Even if the script was installed into `.venv/bin/gooey_test` using `setuptools`, the file still wouldn't exist in the current directory.  So I this may be a bigger question on whether support for entry scripts can be supported with `gooey`.
possible to make this work with Poetry?
```json
  "target": "'<snip>/.venv/bin/python' -u 'gooey_test'",
```
![RunScreen](https://user-images.githubusercontent.com/31610422/106709137-ebce2980-65a8-11eb-9a01-cedaaa227600.png)
